on:
  issues:
    types: [opened, edited]
jobs:
  check-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check Issue title
        run: |
          if [[ "${{ github.event.issue.title }}" =~ ^Bug:.* ]]; then
              echo "ISSUE_TITLE_VALID=true" >> $GITHUB_ENV
          else
              echo "ISSUE_TITLE_VALID=false" >> $GITHUB_ENV
          fi
      # - name: Check Issue body
      #   run: |
      #     if [[ "$TEXT" =~ "(^## Summary$(.|\n)*## Environment$(.|\n)*## Steps to reproduce$(.|\n)*## Expected result$(.|\n)*## Actual result$(.|\n)*$" ]]; then
      #         echo "ISSUE_BODY_VALID=true"
      #     else
      #         echo "ISSUE_BODY_VALID=false"
      #     fi

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.comment.body }}
          regex: '^## Summary$(.|\n)*## Environment$(.|\n)*## Steps to reproduce$(.|\n)*## Expected result$(.|\n)*## Actual result$(.|\n)*$'

      - name: debug
        run: |
          echo "${{ steps.regex-match.outputs.match }}"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Пожалуйста, используйте шаблон для баг-репорта

            Заголовок: `Bug: заголовок`

            ```markdown
            ## Summary
            краткое, емкое и понятное описание ошибки
            ## Environment
            ссылка на билд/коммит/версия ПО и всего окружения
            ## Steps to reproduce
            Полный перечень шагов для воспроизведения
            ## Expected result
            какой результат должен был быть без ошибки
            ## Actual result
            какой результат получился на самом деле
            ```

      # - uses: dessant/label-actions@v2
      #   with:
      #     github-token: ${{ github.token }}
      #     config-path: '.github/label-actions.yml'

      # - if: startsWith(github.event.issue.title, 'ABC-') != 'true'
      #   name: Close Issue
      #   uses: peter-evans/close-issue@v2
      #   with:
      #     comment: |
      #       Issue title must start with 'ABC-'.
      #       Auto-closing this issue.
