on:
  issues:
    types: [opened, edited]

jobs:
  auto_close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Automatically close
        uses: lucasbento/auto-close-issues@v1.0.2
        with:
          github-token: ${{ secrets.token }}
          issue-close-message: "@${issue.user.login}: hello! :wave:\n\nThis issue is being automatically closed."